/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hiconic.devrock.gradle.test.model;

import com.braintribe.common.artifact.ArtifactReflection;

import hiconic.devrock.gradle._TestModel_;

public class Library {
    public boolean someLibraryMethod() {
    	ArtifactReflection reflection = _TestModel_.reflection;
    	_TestModel_.reflection.artifactId();
    	
        return true;
    }
}
